### ISSUE TITLE
JAVA "Error: Could not find or load main class main" - SOLVED in CMD (W10), add solution to atom-script

### ISSUE THREAD

**Issue by createdbyjurand** [atom-community/atom-script#1470] opened 2017-10-29 00:57 UTC
I made a test file "main.java":

--------------------------- start ---------------------------
import java.util.*;
import java.lang.*;
import java.io.*;

class Test {
  public static void main (String[] args) throws java.lang.Exception {
    System.out.println("test");
  }
}
--------------------------- end ---------------------------

I got an error:
"Error: Could not find or load main class main"

Solution 1 - filename should have the same name as class, so renaming file to Test.java can fix that.

but

Solution 2 - in Windows 10 x64 cmd.exe, when you run command "java -cp . Test" or java -classpath . Test" everything works, because it also looks in local directory.

If you add to classpath ".;" ( c:\Program Files\Java\jre1.8.0_152\lib\rt.jar;. ) in cmd.exe command "java Test" starts to run and everything is ok.

However in atom-script still throws error "Error: Could not find or load main class main".

Could you fix it?

**Comment by invinciblerishu** [comment] 2018-08-24 06:41
you need to make your main class public

**Comment by rushikeshmore** [comment] 2018-10-01 15:37
Reinstall JDK

**Comment by Karan102pal** [comment] 2018-10-28 10:55
Its already public!!!

**Comment by gitvivekgupta** [comment] 2019-02-04 09:00
+1

Error: Could not find or load main class sun.applet.AppletViewer
Caused by: java.lang.ClassNotFoundException: sun.applet.AppletViewer

Process finished with exit code 1

**Comment by MARSHAL260** [comment] 2019-04-21 15:57
did every thing but still giving error "could not find or load main class"

**Comment by joandylevi** [comment] 2019-11-09 17:28
https://icetutor.com/question/error-could-not-find-or-load-main-class/

**Comment by ADepic** [comment] 2020-03-30 20:23
For me, `java Testfile.java` works in terminal.
However, this is the command that is run in script package:
`bash -c 'javac -J-Dfile.encoding=UTF-8 -sourcepath '/home/superuser/Desktop/java test_ folder structure' -d /tmp '/home/superuser/Desktop/java test_ folder structure/java test project/src/com/testproject/Testfile.java' && java -Dfile.encoding=UTF-8 -cp /tmp java test project/src/com/testproject.Testfile'`

**Comment by ADepic** [comment] 2020-03-30 20:39
Edited the source code so that the command now is 
`java  '/home/superuser/Desktop/java test_ folder structure/java test project/src/com/testproject/Testfile.java'`

and it still gives me the error. Copying that exact command into the terminal does not give me that error. So what is the problem?

**Comment by aminya** [comment] 2021-05-12 04:50
Should be fixed in #2470. Let me know if it is not.

**Closed by aminya** 2021-05-12 04:50 UTC
