### ISSUE TITLE
gnuplot scripts do not run anymore after update

### ISSUE THREAD

**Issue by vetterl** [atom-community/atom-script#2452] opened 2021-04-21 07:52 UTC
Cannot run gnuplot scripts anymore.
It throws an error message: "Command not configured for gnuplot"

used to work before I updated the script package on 20 april 2021.

**Comment by aminya** [comment] 2021-05-10 05:28
Could you provide a reproduction script?

**Comment by vetterl** [comment] 2021-05-13 14:11
Hi,
see below for a minimal example. I also attached a screenshot of atom when I try to run the script with cmd+i (on a mac). note that I do have language-gnuplot-atom installed, and it worked prior to the March update.
Thanks for the help
Lisa

reset
set term pdfcairo color dashed enhanced size 15 cm, 10 cm

set output “myplot.pdf"

set key noauto bottom
set xlabel “x"
set ylabel “f(x)"

f(x) = x/(1 + x)

plot f(x) w l lw 2

set output

**Comment by aminya** [comment] 2021-05-15 13:55
@vetterl I made a change that fixes the error you mentioned:
https://github.com/atom-community/atom-script/commit/0fbaf4902393ad9c658fd8158bc07f2324dd8e86

But I get a new error:

```
"C:\Users\aminy\Documents\GitHub\JavaScript\@atom-ide-community\atom-script\examples\gnuplot.gp" line 4: internal error : STRING operator applied to undefined or non-STRING variable
```

I am not familiar with Gnuplot code. Is this expected?

**Comment by aminya** [comment] 2021-05-15 14:00
The issue was with the quotation marks which were not standard when I copy-pasted them. The issue is fixed in the latest version now.

**Closed** 2021-05-15 13:59 UTC
Labels: bug
