### ISSUE TITLE
bash: javac: command not found

### ISSUE THREAD

**Issue by AdonisN** [atom-community/atom-script#1809] opened 2019-02-10 16:29 UTC
I have this Java program:
-----------------------------------------------------------------------
public class third{
  public static void main(String[] args) {
    int a = 0;
    String b = "There " + (a > 1 ? " are " + x + " cookies" : "is one cookie") + " in the jar.";
    System.out.println(b);
  }
}
-----------------------------------------------------------------------
But I get this error instead:
"bash: javac: command not found"
Why?

**Comment by hyobyun** [comment] 2019-02-14 15:26
You need to add the java bin directory into your environment path. Something like https://stackoverflow.com/questions/9612941/how-to-set-java-environment-path-in-ubuntu. 

Google "Add java path {YOUR OS} "

**Comment by cyw500** [comment] 2020-02-23 00:41
create a variable JAVA_HOME = /usr/.....
in ~/.bashrc still didn't get it working. Any other package or step please

**Comment by aminya** [comment] 2021-05-12 04:58
Duplicate of https://github.com/atom-community/atom-script/issues/808

**Closed by aminya** 2021-05-12 04:58 UTC
