### ISSUE TITLE
Java execution v3.14.1 ok / v3.15 broken

### ISSUE THREAD

**Issue by bodak** [atom-community/atom-script#1346] opened 2017-05-26 13:57 UTC
OS: Mac Sierra ; Atom 1.17.2 ; Atom-script v3.15
Issue: Error on running java file.

javac: invalid flag: ##final part of java folder path ##
Usage: javac <options> <source files>
use -help for a list of possible options

Something probably broke in this last commit?

https://github.com/rgbkrk/atom-script/commit/b6a682ce70fbbfb2569025547a90a1921289e2e3#diff-99a14086cd9bd6e42dd51f2db939fda7

**Comment by bodak** [comment] 2017-06-02 08:59
add pull request #1353

**Comment by DoctorRios** [comment] 2017-06-07 17:18
Having same issue

**Comment by ashcoding** [comment] 2017-06-28 12:44
Have issues with 3.15.0. `Could not find or load main class` on a MacOS. Java can't run after compiling.
Installed 3.14.1, works fine.

**Comment by ashcoding** [comment] 2017-09-21 05:21
Is this fixed in 3.16.0?

**Comment by ashcoding** [comment] 2017-09-29 13:27
I just tried it out. Same error. 3.16.0 doesn't work. 3.14.1 was the last working version for Mac. Thanks!

**Comment by ashcoding** [comment] 2017-09-29 13:32
I'll just update myself. Apparently, 3.16.0 is working if you are inside the project folder. If you are in a sub folder, it's assuming it's a package. I guess it's working as intended...

3.14.1 didn't care if you are in a sub folder.

So I guess it's working for Mac. 😄

**Comment by aminya** [comment] 2021-05-12 04:55
Should be fixed in #2470. Let me know if it is not.

**Closed by aminya** 2021-05-12 04:55 UTC
